const FOREGROUND_PRIMARY = '#7bc3ff'
const FOREGROUND_ALERT = '#ff3f85'
const FOREGROUND_DISABLED = '#767676'

const BACKGROUND_PRIMARY = '#1b1b1b'


export default {
    FOREGROUND_PRIMARY,
    BACKGROUND_PRIMARY,
    FOREGROUND_ALERT,
    FOREGROUND_DISABLED
}
